@TmsApi_HostAddress = http://localhost:5244

Get http://localhost:5244/api/enrollments
# x-training: dan
# Accept: application/json

Content-Type: application/json
{"studentId":"S-001","courseCode":"CS-101"}
###
